function [FitResult, GoF, RL] = StepSteerFyResponseFit( t, Fy, V)
%CREATEFITS(X,Y)
%  Create fits.
%
%  Data for 'First Order' fit:
%      X Input : x
%      Y Output: y
%  Data for 'Second Order' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Apr-2021 10:37:30

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
FitResult = cell( 2, 1 );
GoF = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'First Order'.
[xData, yData] = prepareCurveData( t, Fy );

% Set up fittype and options.
ft = fittype( 'A*(1-exp(-t/tau))', 'independent', 't', 'dependent', 'Fy' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0];
opts.StartPoint = [1 0.05];
opts.Upper = [Inf Inf];

% Fit model to data.
[FitResult{1}, GoF(1)] = fit( xData, yData, ft, opts );

%% First Order RL calculation.
CurveFitValues = coeffvalues(FitResult{1}); %extract coefficients from the curve fitting
Tau = CurveFitValues(2); %extract tau from the curve fitting coefficients
        
RL = Tau.*mode(V); %obtain the relaxation length values  

%% Fit: 'Second Order'.
%comment on why this part is commented out
%{
[xData, yData] = prepareCurveData( t, Fy );

% Set up fittype and options.
ft = fittype( 'K*(1 - sqrt((zeta*w0)^2 + w0*sqrt(1-zeta^2))/(w0*sqrt(1-zeta^2))*exp(-zeta*w0*t)*sin(w0*sqrt(1-zeta^2)*t+acos(zeta)))', 'independent', 't', 'dependent', 'Fy' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 0];
opts.StartPoint = [1 10 0.5];
opts.Upper = [Inf Inf 1];

% Fit model to data.
[FitResult{2}, GoF(2)] = fit( xData, yData, ft, opts );
%}
